# golangci-lint configuration for high-quality Go code
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Enabled by default
    - errcheck      # Checks for unchecked errors
    - gosimple      # Simplifies code
    - govet         # Go vet examines code
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced Go linter
    - typecheck     # Type-checks Go code
    - unused        # Checks for unused code
    
    # Additional recommended linters
    - bodyclose     # Checks HTTP response body is closed
    - dogsled       # Checks for too many blank identifiers
    - durationcheck # Checks for duration multiplication
    - errorlint     # Finds code that will cause problems with error wrapping
    - exhaustive    # Checks exhaustiveness of enum switch statements
    - gocognit      # Computes cognitive complexity
    - goconst       # Finds repeated strings that could be constants
    - gocritic      # Opinionated Go linter
    - gocyclo       # Computes cyclomatic complexity
    - gofmt         # Checks if code is gofmt-ed
    - goimports     # Checks import order
    - goprintffuncname # Checks printf-like functions
    - gosec         # Inspects source code for security problems
    - misspell      # Finds commonly misspelled English words
    - nakedret      # Finds naked returns
    - nilerr        # Finds the code that returns nil even if it checks that the error is not nil
    - nolintlint    # Reports ill-formed or insufficient nolint directives
    - prealloc      # Finds slice declarations that could potentially be preallocated
    - revive        # Fast, configurable, extensible linter
    - stylecheck    # Replacement for golint
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters
    - whitespace    # Tool for detection of leading and trailing whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    
  govet:
    enable-all: true
    
  gocyclo:
    min-complexity: 15
    
  gocognit:
    min-complexity: 20
    
  goconst:
    min-len: 2
    min-occurrences: 3
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
      
  goimports:
    local-prefixes: github.com/yourusername/streaming-platform-api
    
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    
  gosec:
    excludes:
      - G104 # Audit errors not checked - we use errcheck for this
      
  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        
    # Exclude known linters from partially hard-vendored code
    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec
        
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 3
  
  # Show only new issues
  new: false
  
  # Fix found issues (if it's supported by the linter)
  fix: false
