run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    disable:
      - fieldalignment

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - errcheck
      text: "Error return value.*is not checked"
