run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/websocket/
      linters:
        - errcheck
    - path: cmd/api-server/main.go
      linters:
        - errcheck
